"""Render publication copy from the validated complete study; never publish it."""
import csv,json,re
from pathlib import Path
HERE=Path(__file__).resolve().parent
FAMILY_LABELS={'attribution':'Attribution','authority':'Task and authority','coordination':'Coordination and answer use','techniques':'Security technique outcomes','persistence':'Persistence and external communication','impact':'Scale and impact','recovery':'Cleanup and recovery','chronology':'Chronology and causes'}

def table(headers,rows):
 return '\n'.join(['| '+' | '.join(headers)+' |','| '+' | '.join('---'for _ in headers)+' |']+['| '+' | '.join(map(str,r))+' |'for r in rows])

def main():
 d=json.loads((HERE/'results/study/analysis.json').read_text());assert d['complete'],'Complete review required before rendering publication copy.'
 cohorts={r['scope']:r for r in d['cohort_summary']};main=cohorts['main'];pair=next(r for r in d['paired_summary']if r['selection']=='corrected_primary'and r['budget_min']=='all')
 qrows=[[FAMILY_LABELS[r['family']],r['supported'],r['problem'],r['problem_excluding_disputed'],r['not_discussed']]for r in d['primary_questions']]
 primary_paragraph=f"Every primary report contained useful supported analysis. **{main['with_problem']} of the 113 also contained at least one contradicted or insufficiently supported conclusion** within our eight questions. Excluding disputed interpretations reduces that count to **{main['with_problem_excluding_disputed']}**. In {main['with_support_and_problem_in_same_question']} reports, useful analysis and a flagged conclusion appeared within the same question."
 acknowledgment_text=('No repair transition explicitly acknowledged the earlier problem' if pair['explicit_repair_acknowledgments']==0 else f"{pair['explicit_repair_acknowledgments']} repair transitions explicitly acknowledged the earlier problem")
 parent_problems=pair['parent_problem_claims'];fixed=pair['problem_corrected_statement'];qualified=pair['problem_qualified_statement'];retained=pair['problem_retained_problem'];omitted=pair['problem_omitted']
 pair_results=f"Across the 78 continuations with verified parent mappings, {pair['pairs_with_parent_problem']} began from a report with at least one flagged conclusion. We mapped {parent_problems} parent claim entries with a contradiction or support problem. Of these, {fixed} {'was' if fixed==1 else 'were'} corrected, {qualified} became appropriately qualified, {retained} remained problematic, and {omitted} disappeared from the follow-up. The other transitions are shown below. These are grouped claim entries, not independent observations.\n\nAt the report-pair level, {pair['pairs_with_correction_or_qualification']} continuations corrected or qualified at least one flagged parent claim, {pair['pairs_with_retained_problem']} retained at least one, and {pair['pairs_with_new_problem']} introduced at least one new or materially changed problematic claim. These groups overlap. The new-or-changed total comprises {pair['new_unmapped_problem_claims']} unmatched new entries and {pair['changed_problem_claims']} problematic superseding entries, deduplicated within the follow-up. Published finding coverage increased in {pair['coverage_increased']} continuations; {pair['coverage_increased_with_retained_problem']} of those still retained at least one flagged parent claim. The score gains concern recovered reference findings and do not establish that retained claims were repaired. {acknowledgment_text}; a changed statement alone does not establish a correction in the investigator's internal understanding."
 pair_labels=[('Corrected statement','corrected_statement'),('Appropriately qualified statement','qualified_statement'),('Retained problem','retained_problem'),('Omitted','omitted'),('Materially superseded','superseded'),('Unassessable transition','unassessable'),('Retained supported after comparison','retained_supported')]
 pt=table(['Disposition of a flagged parent claim','All flagged entries','Excluding disputed claim/transition readings'],[[name,pair['problem_'+key],pair['strict_problem_'+key]]for name,key in pair_labels])
 followup=f"Of the 78 continuations, {pair['pairs_with_parent_problem']} started from a report with at least one flagged conclusion. **{pair['pairs_with_correction_or_qualification']} of those corrected or properly qualified at least one such conclusion.** Excluding disputed readings leaves {pair['pairs_with_correction_or_qualification_excluding_disputed']} with a repair. Meanwhile, {pair['pairs_with_retained_problem']} retained at least one problem, and {pair['pairs_with_new_problem']} introduced a new or materially changed problematic claim. These groups overlap: an investigator could repair one conclusion while weakening another.\n\nAcross the {parent_problems} flagged parent claim entries, {fixed} {'was' if fixed==1 else 'were'} corrected and {qualified} gained an adequate qualification; {retained} remained problematic. Another {omitted} were omitted. We did not count disappearance as correction. The [full transition record](/insights/evidence/dsewiki/claim-transitions.csv) shows what changed in each comparison."
 score_text=table(['Finding-coverage rank third','Reports','With a flagged conclusion','Excluding disputed judgments','Median finding coverage'],[[r['scope'].split('_')[0].capitalize(),r['reports'],r['with_problem'],r['with_problem_excluding_disputed'],f"{r['median_finding_coverage']:.3f}"]for r in d['score_strata']])
 score_text+='\n\nThese fixed rank thirds describe the primary collection, with ties ordered by stable report ID. They are not calibrated risk bands or a causal test. Report-level flags are not severity-weighted, and a higher reconstruction score does not certify that every consequential claim is supported.'
 secondary_keys=['provider_swap','earlier_provider_ablation','exploratory_followup','synthesis_accepted','synthesis_rejected']
 secondary_names=['Later provider-name substitutions','Earlier substitutions','Exploratory follow-ups','Accepted synthesis','Rejected synthesis attempts']
 st=table(['Collection','Artifacts','With supported analysis','With a flagged conclusion','Excluding disputed judgments'],[[name,cohorts[key]['reports'],cohorts[key]['with_supported_conclusion'],cohorts[key]['with_problem'],cohorts[key]['with_problem_excluding_disputed']]for key,name in zip(secondary_keys,secondary_names)])
 score_finding=f"Of the 78 follow-ups, **{pair['coverage_increased']} earned a higher score for recovering findings from the original human account. Yet {pair['coverage_increased_with_retained_problem']} of those still carried at least one earlier claim that contradicted the records or went beyond what they established.** Excluding claim and transition judgments we marked disputed leaves **{pair['coverage_increased_with_retained_problem_excluding_disputed']} of those {pair['coverage_increased']}**. We checked the claims separately from the benchmark's grades."
 article_primary=f"All 113 original reports contained useful, supported analysis. **{main['with_problem']} also contained at least one flagged conclusion.** When we excluded interpretations we marked disputable, the count fell to **{main['with_problem_excluding_disputed']}**. Useful findings and unsupported conclusions often appeared in the same report."
 article_repairs=f"Of the 78 follow-ups, {pair['pairs_with_parent_problem']} began with at least one claim we had flagged. We found a correction or an adequate qualification in **{pair['pairs_with_correction_or_qualification']} of those {pair['pairs_with_parent_problem']}**. Excluding disputed readings leaves **{pair['pairs_with_correction_or_qualification_excluding_disputed']}**. Meanwhile, {pair['pairs_with_retained_problem']} retained at least one earlier problem.\n\nAcross all 78 follow-ups, {pair['pairs_with_new_problem']} introduced a new or materially changed problematic claim. These groups overlap: the same report could improve one conclusion and weaken another. We did not count a claim disappearing as a correction. The [claim comparisons](/insights/evidence/dsewiki/claim-transitions.csv) show what changed."
 article_score=f"**{pair['coverage_increased']} follow-ups earned a higher score. Of those, {pair['coverage_increased_with_retained_problem']} still carried at least one earlier claim we flagged.** Some of our judgments are contestable. Even after excluding disputed judgments, **{pair['coverage_increased_with_retained_problem_excluding_disputed']} of the {pair['coverage_increased']}** retained an earlier problem."
 article_repair_summary=f"Of the 78 follow-ups, {pair['pairs_with_parent_problem']} started from a report with at least one claim we flagged. **Only {pair['pairs_with_correction_or_qualification']} of those {pair['pairs_with_parent_problem']} corrected or properly narrowed any flagged claim.** Excluding judgments we marked disputable leaves {pair['pairs_with_correction_or_qualification_excluding_disputed']} clear case."
 article_repair_detail=f"Of the {pair['pairs_with_parent_problem']} follow-ups that started with a flagged claim, {pair['pairs_with_retained_problem']} retained at least one earlier problem. Across all 78 follow-ups, {pair['pairs_with_new_problem']} introduced a new or materially changed claim that we flagged. These groups overlap: the same report could correct one conclusion and weaken another."
 replacements={
 'ARTICLE_SCORE_FINDING':article_score, 'ARTICLE_REPAIR_SUMMARY':article_repair_summary, 'ARTICLE_REPAIR_DETAIL':article_repair_detail,
 'FOLLOWUP_SCORE_FINDING':score_finding, 'ARTICLE_PRIMARY_RESULTS':article_primary, 'ARTICLE_REPAIR_RESULTS':article_repairs,
 'PRIMARY_FLAGS':str(main['with_problem']),'PRIMARY_STRICT_FLAGS':str(main['with_problem_excluding_disputed']),
 'PAIR_ABSTRACT':f"Among the {pair['pairs_with_parent_problem']} continuations with a flagged parent conclusion, {pair['pairs_with_correction_or_qualification']} correct or adequately qualify at least one such claim ({pair['pairs_with_correction_or_qualification_excluding_disputed']} excluding disputed readings), while {pair['pairs_with_retained_problem']} retain a problem. Across all 78 continuations, {pair['pairs_with_new_problem']} introduce a new or materially changed problematic claim. These groups overlap.",
 'PRIMARY_RESULTS':primary_paragraph+f" The median report discusses {main['median_questions_discussed']} questions, contains supported analysis in {main['median_supported_questions']} questions and a flagged conclusion in {main['median_problem_questions']} questions. Of the 113 reports, {main['with_contradiction']} contain a claim coded as contradicted by the records ({main['with_contradiction_excluding_disputed']} excluding disputed readings). This narrower category is distinct from an inference judged to need stronger support. The condition-specific counts remain in the downloadable results and are descriptive only.",
 'PRIMARY_QUESTION_TABLE':table(['Question','Supported analysis','Flagged conclusion','Flagged, excluding disputed','Not discussed'],qrows),
 'PAIR_RESULTS':pair_results,'PAIR_TABLE':pt,'SCORE_RESULTS':score_text,
 'SECONDARY_RESULTS':'The secondary collections also contain both useful analysis and conclusions requiring stronger support. Their separate denominators preserve the experiment structure; pooling them with the primary reports would obscure shared inputs, continuations and failed attempts.',
 'SECONDARY_TABLE':st,'PRIMARY_PARAGRAPH':primary_paragraph,'FOLLOWUP_PARAGRAPHS':followup,
 }
 # Use native, accessible HTML for the existing MDX article table.
 headers=['Question','Supported analysis','Flagged conclusion','Flagged, excluding disputed']
 html=['<div className="my-6 overflow-x-auto" role="region" aria-label="Evidence assessment of 113 primary reports" tabIndex={0}>','<table className="w-full min-w-[600px] text-left text-sm leading-relaxed">','<caption className="sr-only">Reports with at least one conclusion in each category, out of 113. Columns overlap.</caption>','<thead className="bg-forest-50"><tr>'+''.join(f'<th scope="col" className="px-4 py-3">{h}</th>'for h in headers)+'</tr></thead>','<tbody>']
 for row in qrows:html.append('<tr className="border-t border-rule"><th scope="row" className="px-4 py-4 font-medium">'+str(row[0])+'</th>'+''.join(f'<td className="px-4 py-4 tabular-nums">{x}</td>'for x in row[1:4])+'</tr>')
 html+=['</tbody></table></div>'];replacements['QUESTION_TABLE']='\n'.join(html)
 def render(filename):
  text=(HERE/filename).read_text()
  for key,value in replacements.items():text=text.replace('{{'+key+'}}',value)
  assert not re.search(r'\{\{[A-Z_]+\}\}',text)
  return text
 paper=render('paper-template.md')
 urls={r['review_id']:r['source_url'].replace('raw.githubusercontent.com/hamzah2304/messageboardauditbench/','github.com/hamzah2304/messageboardauditbench/blob/')for r in csv.DictReader((HERE/'results/study/coverage.csv').open())}
 paper=re.sub(r'\bC\d{3}\b',lambda m:f'[{m.group()}]({urls[m.group()]})'if m.group()in urls else m.group(),paper)
 (HERE/'paper.md').write_text(paper)
 (HERE/'insights-body.mdx').write_text(render('insights-template.mdx'))
 newsletter=render('newsletter-template.md')
 (HERE/'newsletter.md').write_text(newsletter)
 print('Rendered methods paper, Insights body and newsletter from complete validated results.')
if __name__=='__main__':main()
